### PR TITLE
Lift requirements into environment.yml explicitly

### PR DESCRIPTION
**Pull request by tomalrussell**
Should help micromamba build the env, as it didn't handle the
`-r requirements.txt` reference for pip.

### CODE REVIEW

**Comment by thomas-fred** [comment]
Delete the `requirements.txt` too?

**Comment by tomalrussell** [comment]
Can you reproduce the test failure locally? I'll try on a linux machine when possible - the failure is in the image comparison test for make_exposure_img.

**Comment by tomalrussell** [comment]
Looks like a minor difference in font rendering:

Actual

actual

Expected

expected

**Comment by thomas-fred** [comment]
Hmm, yeah it is the text rendering isn't it. So the images are different...

Matplotlib is pinned, but perhaps actual and expected were generated with different backends.

Oh the complexities of comparing plotted output from multiple machines.

**Comment by thomas-fred** [comment]
I'm setting up `open-gira` on virtualised Ubuntu 20.04, will give it a go locally in a moment.

**Comment by thomas-fred** [comment]
Ok, so for test_make_exposure_img.py, the CI is passing and is using the matplotlib backend of 'agg' (the default, builtin backend). On my local machine which is failing, I'm using the same backend. So that's probably not the problem.

**Comment by thomas-fred** [comment]
Yeah it fails locally for me too.

**Comment by thomas-fred** [comment]
So I suppose some of the packages that conda is now installing directly rather than delegating to pip are different. I was wondering about something like `Pillow` that's pretty low level, does text rendering for images.

**Comment by thomas-fred** [comment]
If it's failing everywhere, but it's only a text difference, perhaps just update the image -- I have no great desire to delve deeper.

**Pull request closed without merging**
