### PR TITLE
83 create rail networks (and rework testing)

### PR DESCRIPTION
**Pull request by thomas-fred**
Create rail networks from OSM data.

Lines are those tagged as `railway=rail` which are:
> Full sized passenger or freight trains in the standard gauge for the country or state.

I've also included the `railway=station` [nodes](https://user-images.githubusercontent.com/39301725/181038536-cf13cd06-f6ec-4ce6-950a-60830a6e9125.svg).

The above required propagating nodes from the OSM extracted data which we didn't previously do.

Creation and annotation of a given network type is now incorporated in the same rule/script. I couldn't see the point of separating them given creation fed into (only) annotation.

Common functionality for creating road and rail networks has been pulled out into a `scripts/transport/utils.py` module.

Addresses #83.

### CODE REVIEW

**Comment by thomas-fred** [comment]
Need to remake test output as I've touched `osm_to_pq.py` :sob:

**Comment by thomas-fred** [comment]
20220726_rail_and_road_egypt

Road and rail networks (stations marked) for Egypt.

**Comment by thomas-fred** [comment]
As part of this PR I've also reworked the testing code.

The tests are now split into `integration` and `unit` tests. Most of what were in `tests/unit` are now in `tests/integration`, as they test both workflow scripts but also snakemake rule logic. The `tests/unit` directory holds tests for small units of logic like functions or classes.

The snakemake test runner previously known as `common.py` is now `runner.py`. The test runner now includes more of the snakemake execution, so the test defintions are simpler (a rule name and a target list). The test output checker now can perform visual comparison of image files, which is superior to the binary comparison of before as many image files encode a write time or a version number in the file which will break binary equality but not affect visual equality.

The default test case is now the country of Djibouti rather than a small slither of Tanzania (`tanzania-mini`). Djibouti is still small enough for tests to run very quickly, but it has both road and rail networks, rivers, and a coastline. The test config now uses 4 slices rather than 1, so it tests splitting and joining logic for the relevant rules. Creating test data is easier as it's just the country of Djibouti rather than different slices of certain pieces of Tanzania. Despite the change, other tests could be added in future with input data from other countries.

**Comment by thomas-fred** [comment]
@tomalrussell can you give this a look over when you're back? Sorry for the large PR, but as I was writing tests I felt like the testing could be made cleaner.

**Review by tomalrussell — APPROVED** [review]
Looks good - the changes to the test structure are clear, and keeping the network generation generic where possible looks clean too.

Minor suggestions that crossed my mind as reading a couple of utils functions.. otherwise happy to merge and keep building on this.

**Pull request merged**
