### PR TITLE
Doc/onboarding

### PR DESCRIPTION
**Pull request by mjaquiery**
This addresses #33 .

We have a new doc folder with a README.md file that takes new users through the whole workflow process, including inspecting each of the different files as they go and looking at what the program is doing at each stage. 
It includes a bunch of QGIS screenshots to show what output should look like, too.

I also wrote a Dockerfile that implements the workflow I've documented in the new user guide.
I could perhaps point users towards that Dockerfile if they're doing the install-via-pip approach?

## Possible considerations before merge:
- Do we want a separate new user guide, and is a markdown document sufficient?
  - It would not be hard to make this into a static website (e.g. Jekyll served with GHPages), but perhaps that's too heavyweight a solution?
  - If we did that we'd have easy scope for expanding the documentation, if we see this project being in need of heavy documentation.
  - We could merge the new user guide with the general README, but that might be too cluttered.
- The tests are being failed -- this might be something to do with permissions/branches?
  - I haven't changed any files that the tests key on, I've only changed .md files and added images
- I've only done minor tweaks to the base README -- we might want that updated in the same PR?

### CODE REVIEW

**Comment by tomalrussell** [comment]
> QGIS screenshots

It really helps to include these. I think we can assume a little familiarity with QGIS (and point to their intro docs if not) and make the screenshots a bit more informative with the flood layer coloured white-to-blue for flooding, and in the final shot also colouring roads by one of the hazard columns, to show that the values are now attributed to the road segments.

> Dockerfile

Super useful to have the environment encapsulated. I wonder if it would be worth moving some of the steps out of the Dockerfile itself - moving the two short download scripts into the snakemake workflow, and dropping the snakemake commands from the end of the Dockerfile, instead adding a section somewhere in the docs which steps through building the file and running those commands (with a mounted volume, so the files are easily accessible to QGIS or later processing):
- clone this repo
- docker build
- docker run ... (maybe defaults to snakemake all?)

> separate new user guide

The separate markdown document is good to start. Good idea to add some structure for future expansion. GH Pages is convenient - maybe with [mdBook](https://rust-lang.github.io/mdBook/index.html) which gives a clean output and is built on top of markdown files directly. [Example GitHub Action](https://github.com/rust-lang/mdBook/wiki/Automated-Deployment%3A-GitHub-Actions#github-pages-deploy) to build mdbook and deploy to pages.

> tests are being failed

This is unrelated to any changes here, seems to be some library assumption has changed and outputting float64 not float32, see [logs](https://github.com/nismod/open-gira/runs/4965065305?check_suite_focus=true#step:7:82)

> tweaks to the base README

fine to include these in this PR.. though might be worth pushing those straight to master as we work on this a little more.

**Review by tomalrussell — CHANGES_REQUESTED** [review]
Thanks for this, really clear outline of the workflow and nice tone in the text :)

I put a few notes in a comment on the PR, happy to chat about them some time too.

**Comment by mjaquiery** [comment]
> > QGIS screenshots
> 
> It really helps to include these. I think we can assume a little familiarity with QGIS (and point to their intro docs if not) and make the screenshots a bit more informative with the flood layer coloured white-to-blue for flooding, and in the final shot also colouring roads by one of the hazard columns, to show that the values are now attributed to the road segments.
> 
For the moment I'm leaving them as they are, but I think that's very fair. Once I've set up filtering before slicing I'll be able to produce some nicer ones. In the meantime I've just made one at the very end with some flood shading.

We can't do the last bit -- values attributed to road segments, because the final output is a .geoparquet file rather than a .osm.pbf file. I guess we could convert back?

> > Dockerfile
> 
> Super useful to have the environment encapsulated. I wonder if it would be worth moving some of the steps out of the Dockerfile itself - moving the two short download scripts into the snakemake workflow, and dropping the snakemake commands from the end of the Dockerfile, instead adding a section somewhere in the docs which steps through building the file and running those commands (with a mounted volume, so the files are easily accessible to QGIS or later processing):
> 
>     * clone this repo
> 
>     * docker build
> 
>     * docker run ... (maybe defaults to snakemake all?)
> 
Done this now, it works well, I think.

> 
> > separate new user guide
> 
> The separate markdown document is good to start. Good idea to add some structure for future expansion. GH Pages is convenient - maybe with [mdBook](https://rust-lang.github.io/mdBook/index.html) which gives a clean output and is built on top of markdown files directly. [Example GitHub Action](https://github.com/rust-lang/mdBook/wiki/Automated-Deployment%3A-GitHub-Actions#github-pages-deploy) to build mdbook and deploy to pages.
> 
I've set up a mdbook which works on my local machine. We should know fairly soon whether it works, and if not I'll debug it on this branch. If it does then I'll switch the branch trigger to `main`.

> > tests are being failed
> 
> This is unrelated to any changes here, seems to be some library assumption has changed and outputting float64 not float32, see [logs](https://github.com/nismod/open-gira/runs/4965065305?check_suite_focus=true#step:7:82)
> 
Okay. I get emailed after every push 😂 

> > tweaks to the base README
> 
> fine to include these in this PR.. though might be worth pushing those straight to master as we work on this a little more.
May as well have them here, I guess?

## Overall
I think if it's okay with you we'll merge this documentation of the current state when you think it's clear enough, and then modify the workflow etc. and update the documentation as we do? Otherwise this will become a huge 'do everything' PR.

**Review by tomalrussell — APPROVED** [review]

**Comment by tomalrussell** [comment]
Agreed on merging and following up, good to go!

**Pull request merged**
